repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals

  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys, --remove-unused-variables]

  - repo: https://github.com/psf/black
    rev: 23.1.0  # Replace with the latest stable version of Black
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: remove-notebooks-output
        name: Remove Jupyter Notebooks Output
        language: system
        files: \.ipynb$
        entry: jupyter nbconvert --clear-output --inplace
